[mojo-lang] Use Lower Case in TailCallAttribute Member Names (#98253)
The build is broken with the error message:
```
error: declaration of 'mlir::LLVM::tailcallkind::TailCallKind mlir::LLVM::detail::TailCallKindAttrStorage::TailCallKind' changes meaning of 'TailCallKind'
```
I cannot replicate the error locally because I think it's only reported
by GCC not clang. However, I think the change in this patch may fix it.